### ISSUE TITLE
Wrong FWHM for sechfield

### ISSUE THREAD

**Issue by anates014** [xmhk/gnlse#1]
t0 for FWHM-selection in sechfield()-function should be "width/(2_ln(2+sqrt(3))", and not "width/(2_arcsinh(1))"

**Comment by xmhk** [comment]
(i guess this is the wrong repository; the sechfield function is filed under 'optictools')

To be clear, this function calculates the fwhm of the power profile (P proportional to |E|^2) of an electrical field with the shape
E(T) = sech( T/ T0)

the half-width-at-half-maximum (with respect to power) can be calculated from:
  1/2 sech^2(T=0)         = sech^2(T/T0)
<=>
  1/sqrt(2) * sech( T=0)  = sech(T/T0)
=1/sqrt(2) *  1                = sech(T/T0) = 1/cosh(T/T0)
<=> T/T0 =   arcosh(sqrt(2)) = 0.8813735...

tau_fwhm = 2 * T = 2 * 0.881375 * T0

with the identities
arcosh(x) = ln ( x+sqrt(x^2-1))    and  arcsinh = ln( x+sqrt(x^2+1))

you find tau_fwhm = 2 * arcsinh(1) * T0 = 2 * arcosh( sqrt(2) ) * T0 = 2 * arcsech( 1/ sqrt(2)) * T0

PS: have a look at https://en.wikipedia.org/wiki/Inverse_hyperbolic_function and 
http://www.rp-photonics.com/sech2_shaped_pulses.html

**Comment by anates014** [comment]
Point 1: Yes, wrong repository, thanks.
Point 2: Ok, I thought that it is the FWHM of the intensity, and not the power. In this case the current value is correct.
